language: 'php'

php:
  - '7.1'

cache:
  directories:
    - "dev/cache"

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script: vendor/bin/phpunit --coverage-text=php://stdout --colors=never